//! The generated runtime: `Ctx`, `Rt`, `Vars` and `Scheduler`.
//!
//! These four files are the same in every exported mod apart from their package
//! declaration, and between them they are the only generated code that touches
//! Minecraft's own API. That is deliberate: Minecraft renames methods between
//! versions, and when it does, the fix is a few lines in `Rt.java` rather than
//! every call site a canvas produced.
//!
//! Everything is written against the API FrozenLib 3.0-mc26.3 is built on -
//! `Identifier` rather than `ResourceLocation`, `hurtServer`, and so on. A
//! different Minecraft version needs `Rt.java` adjusted, and the header comment
//! in the generated file says so.

use crate::naming::Names;
use crate::writer::Source;

/// Every runtime file, as `(path, contents)`.
pub fn files(names: &Names) -> Vec<(String, String)> {
    vec![
        (names.common("script/Ctx.java"), ctx(names)),
        (names.common("script/Rt.java"), rt(names)),
        (names.common("script/Vars.java"), vars(names)),
        (names.common("script/Scheduler.java"), scheduler(names)),
    ]
}

/// The banner every generated Java file carries.
pub fn banner(source: &mut Source, names: &Names, note: &str) {
    source.comment(&format!(
        "Generated by Stitchcraft from the {} canvas. Edits here are overwritten \
         on the next export.\n\n{note}",
        names.mod_id
    ));
    source.blank();
}

fn ctx(names: &Names) -> String {
    let mut s = Source::new();
    s.line(format!("package {};", names.script_package()));
    s.blank();
    banner(
        &mut s,
        names,
        "One event's context, with a nullable field per thing an event might be \
         about. Every accessor has a default, so a reporter used under a hook \
         that cannot answer it reads as empty rather than throwing out of the \
         handler.",
    );
    s.lines([
        "import net.minecraft.core.BlockPos;",
        "import net.minecraft.core.registries.BuiltInRegistries;",
        "import net.minecraft.server.MinecraftServer;",
        "import net.minecraft.server.level.ServerLevel;",
        "import net.minecraft.server.level.ServerPlayer;",
        "import net.minecraft.world.entity.LivingEntity;",
        "import net.minecraft.world.level.block.state.BlockState;",
        "import org.jetbrains.annotations.Nullable;",
    ]);
    s.blank();
    s.braced("public final class Ctx", |s| {
        s.lines([
            "public final @Nullable MinecraftServer server;",
            "public final @Nullable ServerLevel level;",
            "public final @Nullable BlockPos pos;",
            "public final @Nullable ServerPlayer player;",
            "public final @Nullable LivingEntity entity;",
            "public final @Nullable BlockState state;",
            "public final double damage;",
        ]);
        s.blank();
        s.braced(
            "private Ctx(@Nullable MinecraftServer server, @Nullable ServerLevel level, \
             @Nullable BlockPos pos, @Nullable ServerPlayer player, \
             @Nullable LivingEntity entity, @Nullable BlockState state, double damage)",
            |s| {
                s.lines([
                    "this.server = server;",
                    // A level always knows its server, so one is never missing
                    // when the other is present.
                    "this.level = level;",
                    "this.pos = pos;",
                    "this.player = player;",
                    "this.entity = entity;",
                    "this.state = state;",
                    "this.damage = damage;",
                ]);
            },
        );
        s.blank();
        s.comment("Builders, one per shape of hook.");
        s.braced("public static Ctx of(@Nullable MinecraftServer server)", |s| {
            s.line("return new Ctx(server, null, null, null, null, null, 0.0D);");
        });
        s.blank();
        s.braced("public static Ctx of(ServerLevel level)", |s| {
            s.line("return new Ctx(level.getServer(), level, null, null, null, null, 0.0D);");
        });
        s.blank();
        s.braced("public static Ctx of(ServerLevel level, BlockPos pos)", |s| {
            s.line("return new Ctx(level.getServer(), level, pos, null, null, null, 0.0D);");
        });
        s.blank();
        s.braced(
            "public static Ctx of(ServerLevel level, BlockPos pos, @Nullable BlockState state)",
            |s| {
                s.line("return new Ctx(level.getServer(), level, pos, null, null, state, 0.0D);");
            },
        );
        s.blank();
        s.braced("public static Ctx of(ServerPlayer player)", |s| {
            s.line("return new Ctx(player.getServer(), player.level(), player.blockPosition(), player, null, null, 0.0D);");
        });
        s.blank();
        s.braced("public static Ctx of(LivingEntity entity)", |s| {
            s.open("if (!(entity.level() instanceof ServerLevel level)) {");
            s.line("return new Ctx(null, null, entity.blockPosition(), null, entity, null, 0.0D);");
            s.close("}");
            s.line("final ServerPlayer asPlayer = entity instanceof ServerPlayer p ? p : null;");
            s.line("return new Ctx(level.getServer(), level, entity.blockPosition(), asPlayer, entity, null, 0.0D);");
        });
        s.blank();
        s.braced("public Ctx withPlayer(@Nullable ServerPlayer next)", |s| {
            s.line("return new Ctx(this.server, this.level, next != null ? next.blockPosition() : this.pos, next, this.entity, this.state, this.damage);");
        });
        s.blank();
        s.braced("public Ctx withEntity(@Nullable LivingEntity next)", |s| {
            s.line("return new Ctx(this.server, this.level, next != null ? next.blockPosition() : this.pos, this.player, next, this.state, this.damage);");
        });
        s.blank();
        s.braced("public Ctx withPos(@Nullable BlockPos next)", |s| {
            s.line("return new Ctx(this.server, this.level, next, this.player, this.entity, this.state, this.damage);");
        });
        s.blank();
        s.braced("public Ctx withState(@Nullable BlockState next)", |s| {
            s.line("return new Ctx(this.server, this.level, this.pos, this.player, this.entity, next, this.damage);");
        });
        s.blank();
        s.braced("public Ctx withDamage(double next)", |s| {
            s.line("return new Ctx(this.server, this.level, this.pos, this.player, this.entity, this.state, next);");
        });
        s.blank();
        s.comment(
            "Reporter accessors. Each one has a neutral default, which is what \
             makes a hook that cannot answer a reporter a warning in the editor \
             rather than a crash in the game.",
        );
        s.braced("public String playerName()", |s| {
            s.line("return this.player != null ? this.player.getGameProfile().name() : \"\";");
        });
        s.blank();
        s.braced("public double playerHealth()", |s| {
            s.line("return this.player != null ? this.player.getHealth() : 0.0D;");
        });
        s.blank();
        s.braced("public String playerHeldItem()", |s| {
            s.open("if (this.player == null) {");
            s.line("return \"\";");
            s.close("}");
            s.line("return BuiltInRegistries.ITEM.getKey(this.player.getMainHandItem().getItem()).toString();");
        });
        s.blank();
        s.braced("public double x()", |s| {
            s.line("return this.pos != null ? this.pos.getX() : 0.0D;");
        });
        s.blank();
        s.braced("public double y()", |s| {
            s.line("return this.pos != null ? this.pos.getY() : 0.0D;");
        });
        s.blank();
        s.braced("public double z()", |s| {
            s.line("return this.pos != null ? this.pos.getZ() : 0.0D;");
        });
        s.blank();
        s.braced("public String blockId()", |s| {
            s.open("if (this.state != null) {");
            s.line("return BuiltInRegistries.BLOCK.getKey(this.state.getBlock()).toString();");
            s.close("}");
            s.open("if (this.level != null && this.pos != null) {");
            s.line("return BuiltInRegistries.BLOCK.getKey(this.level.getBlockState(this.pos).getBlock()).toString();");
            s.close("}");
            s.line("return \"\";");
        });
        s.blank();
        s.braced("public String entityType()", |s| {
            s.open("if (this.entity == null) {");
            s.line("return \"\";");
            s.close("}");
            s.line("return BuiltInRegistries.ENTITY_TYPE.getKey(this.entity.getType()).toString();");
        });
        s.blank();
        s.braced("public double entityHealth()", |s| {
            s.line("return this.entity != null ? this.entity.getHealth() : 0.0D;");
        });
        s.blank();
        s.braced("public double damage()", |s| {
            s.line("return this.damage;");
        });
    });
    s.finish()
}

fn rt(names: &Names) -> String {
    let main = &names.main_class;
    let mut s = Source::new();
    s.line(format!("package {};", names.script_package()));
    s.blank();
    banner(
        &mut s,
        names,
        "Every command a canvas can run, and every coercion its values need. \
         This is the only generated file that calls Minecraft's own API, so it \
         is the only one to revisit when a signature changes between game \
         versions.\n\nNothing here throws: a missing level, an unknown id or a \
         zero divisor is a no-op with a warning in the log, because a handler \
         runs inside the server tick and an exception there takes the world \
         down with it.",
    );
    s.lines([
        "import java.util.List;",
        "import java.util.Locale;",
        "import java.util.Optional;",
        "import net.minecraft.core.BlockPos;",
        "import net.minecraft.core.Holder;",
        "import net.minecraft.core.particles.ParticleOptions;",
        "import net.minecraft.core.registries.BuiltInRegistries;",
        "import net.minecraft.network.chat.Component;",
        "import net.minecraft.resources.Identifier;",
        "import net.minecraft.server.MinecraftServer;",
        "import net.minecraft.server.level.ServerLevel;",
        "import net.minecraft.server.level.ServerPlayer;",
        "import net.minecraft.sounds.SoundEvent;",
        "import net.minecraft.sounds.SoundSource;",
        "import net.minecraft.world.effect.MobEffect;",
        "import net.minecraft.world.effect.MobEffectInstance;",
        "import net.minecraft.world.entity.Entity;",
        "import net.minecraft.world.entity.EntityType;",
        "import net.minecraft.world.entity.LivingEntity;",
        "import net.minecraft.world.item.Item;",
        "import net.minecraft.world.item.ItemStack;",
        "import net.minecraft.world.level.Level;",
        "import net.minecraft.world.level.block.Block;",
        "import net.minecraft.world.phys.Vec3;",
        "import org.jetbrains.annotations.Nullable;",
        format!("import {}.{main};", names.package).as_str(),
    ]);
    s.blank();
    s.braced("public final class Rt", |s| {
        s.doc(
            "The most passes a `while` loop gets. A handler runs inside the \
             server tick, so an unterminated loop would hang the game rather \
             than just spin - the exported code trades exactness for a server \
             that stays up.",
        );
        s.line("public static final int LOOP_LIMIT = 100_000;");
        s.blank();
        s.line("public static final Object[] NO_ARGS = new Object[0];");
        s.blank();
        s.line("private Rt() {}");
        s.blank();

        s.comment("── Coercion ──────────────────────────────────────────────");
        s.doc("A value as a number. Text that looks like one counts, and so does a boolean.");
        s.braced("public static double num(@Nullable Object value)", |s| {
            s.line("if (value instanceof Number n) return n.doubleValue();");
            s.line("if (value instanceof Boolean b) return b ? 1.0D : 0.0D;");
            s.open("if (value instanceof String text) {");
            s.open("try {");
            s.line("return Double.parseDouble(text.trim());");
            s.close("} catch (NumberFormatException ignored) {");
            s.line("return 0.0D;");
            s.close("}");
            s.close("}");
            s.line("return 0.0D;");
        });
        s.blank();
        s.braced("public static int integer(@Nullable Object value)", |s| {
            s.line("return integer(num(value));");
        });
        s.blank();
        s.doc("Clamps rather than overflowing, which a plain `(int)` cast would not.");
        s.braced("public static int integer(double n)", |s| {
            s.line("if (!Double.isFinite(n)) return 0;");
            s.line("return (int) Math.max(Integer.MIN_VALUE, Math.min(Integer.MAX_VALUE, n));");
        });
        s.blank();
        s.doc(
            "A value as text. A whole number prints without its decimal point, \
             which is what the editor shows and what a chat message wants.",
        );
        s.braced("public static String str(@Nullable Object value)", |s| {
            s.line("if (value == null) return \"\";");
            s.line("if (value instanceof String text) return text;");
            s.open("if (value instanceof Number n) {");
            s.line("final double d = n.doubleValue();");
            s.line("if (d == Math.rint(d) && Double.isFinite(d)) return Long.toString((long) d);");
            s.line("return Double.toString(d);");
            s.close("}");
            s.line("return String.valueOf(value);");
        });
        s.blank();
        s.doc(
            "A value as a boolean: a non-zero number, or a non-empty string \
             that is not `false`. The same rule the editor applies.",
        );
        s.braced("public static boolean bool(@Nullable Object value)", |s| {
            s.line("if (value instanceof Boolean b) return b;");
            s.line("if (value instanceof Number n) return n.doubleValue() != 0.0D;");
            s.line("if (value instanceof String text) return !text.isEmpty() && !text.equals(\"false\");");
            s.line("return false;");
        });
        s.blank();
        s.doc(
            "Loose equality: numeric when both sides read as numbers, textual \
             otherwise.",
        );
        s.braced("public static boolean eq(@Nullable Object left, @Nullable Object right)", |s| {
            s.open("if (isNumeric(left) && isNumeric(right)) {");
            s.line("return num(left) == num(right);");
            s.close("}");
            s.line("return str(left).equals(str(right));");
        });
        s.blank();
        s.braced("private static boolean isNumeric(@Nullable Object value)", |s| {
            s.line("if (value instanceof Number || value instanceof Boolean) return true;");
            s.line("if (!(value instanceof String text)) return false;");
            s.open("try {");
            s.line("Double.parseDouble(text.trim());");
            s.line("return true;");
            s.close("} catch (NumberFormatException ignored) {");
            s.line("return false;");
            s.close("}");
        });
        s.blank();
        s.doc(
            "One of a custom block's inputs. Which index a named input has is \
             decided at export time, so this only guards against a call site \
             that passed too few - which the editor reconciles, but a \
             hand-edited save can still hold.",
        );
        s.braced("public static Object arg(Object[] args, int index)", |s| {
            s.line("return index >= 0 && index < args.length ? args[index] : Double.valueOf(0.0D);");
        });
        s.blank();

        s.comment("── Arithmetic and text, matching the editor exactly ──────");
        s.braced("public static double div(double left, double right)", |s| {
            s.line("return right == 0.0D ? 0.0D : left / right;");
        });
        s.blank();
        s.doc("Euclidean modulo, so `-1 mod 3` is 2 - the same as the editor.");
        s.braced("public static double mod(double left, double right)", |s| {
            s.line("if (right == 0.0D) return 0.0D;");
            s.line("final double remainder = left % right;");
            s.line("return remainder < 0.0D ? remainder + Math.abs(right) : remainder;");
        });
        s.blank();
        s.doc("Trigonometry is in degrees, as it is in the editor's math block.");
        s.braced("public static double math(String function, double n)", |s| {
            s.open("return switch (function) {");
            s.lines([
                "case \"Abs\" -> Math.abs(n);",
                "case \"Floor\" -> Math.floor(n);",
                "case \"Ceiling\" -> Math.ceil(n);",
                "case \"Sign\" -> Math.signum(n);",
                "case \"Sqrt\" -> Math.sqrt(n);",
                "case \"Sin\" -> Math.sin(Math.toRadians(n));",
                "case \"Cos\" -> Math.cos(Math.toRadians(n));",
                "case \"Tan\" -> Math.tan(Math.toRadians(n));",
                "case \"Asin\" -> Math.toDegrees(Math.asin(n));",
                "case \"Acos\" -> Math.toDegrees(Math.acos(n));",
                "case \"Atan\" -> Math.toDegrees(Math.atan(n));",
                "case \"Ln\" -> Math.log(n);",
                "case \"Log\" -> Math.log10(n);",
                "case \"Log2\" -> Math.log(n) / Math.log(2.0D);",
                "case \"EPower\" -> Math.exp(n);",
                "case \"TenPower\" -> Math.pow(10.0D, n);",
                "default -> 0.0D;",
            ]);
            s.close("};");
        });
        s.blank();
        s.doc("Inclusive on both ends, and whole numbers when both bounds are whole.");
        s.braced("public static double random(double a, double b)", |s| {
            s.line("final double low = Math.min(a, b);");
            s.line("final double high = Math.max(a, b);");
            s.open("if (low == Math.rint(low) && high == Math.rint(high)) {");
            s.line("final long span = (long) high - (long) low + 1L;");
            s.line("return low + Math.floor(Math.random() * span);");
            s.close("}");
            s.line("return low + Math.random() * (high - low);");
        });
        s.blank();
        s.braced("public static boolean chance(double percent)", |s| {
            s.line("return Math.random() * 100.0D < percent;");
        });
        s.blank();
        s.doc("Character count, not UTF-16 length, so an emoji counts as one.");
        s.braced("public static double length(String text)", |s| {
            s.line("return text.codePointCount(0, text.length());");
        });
        s.blank();
        s.doc("1-based, 0 when not found - the editor's convention.");
        s.braced("public static double indexOf(String needle, String haystack)", |s| {
            s.line("if (needle.isEmpty()) return 0.0D;");
            s.line("final int at = haystack.indexOf(needle);");
            s.line("return at < 0 ? 0.0D : haystack.codePointCount(0, at) + 1;");
        });
        s.blank();
        s.braced("public static double lastIndexOf(String needle, String haystack)", |s| {
            s.line("if (needle.isEmpty()) return 0.0D;");
            s.line("final int at = haystack.lastIndexOf(needle);");
            s.line("return at < 0 ? 0.0D : haystack.codePointCount(0, at) + 1;");
        });
        s.blank();
        s.doc("1-based; out of range reads as empty rather than throwing.");
        s.braced("public static String letterOf(double index, String text)", |s| {
            s.line("final int count = text.codePointCount(0, text.length());");
            s.line("final int at = (int) index;");
            s.line("if (at < 1 || at > count) return \"\";");
            s.line("final int start = text.offsetByCodePoints(0, at - 1);");
            s.line("return text.substring(start, text.offsetByCodePoints(start, 1));");
        });
        s.blank();
        s.braced("public static String changeCase(String text, String which)", |s| {
            s.line("return which.equals(\"Upper\") ? text.toUpperCase(Locale.ROOT) : text.toLowerCase(Locale.ROOT);");
        });
        s.blank();
        s.doc(
            "Real-world clock fields, matching the editor's `current (...)` \
             block. Day of week is 1 for Sunday.",
        );
        s.braced("public static double currentTime(String field)", |s| {
            s.line("final java.time.LocalDateTime now = java.time.LocalDateTime.now();");
            s.open("return switch (field) {");
            s.lines([
                "case \"Year\" -> now.getYear();",
                "case \"Month\" -> now.getMonthValue();",
                "case \"Date\" -> now.getDayOfMonth();",
                "case \"DayOfWeek\" -> now.getDayOfWeek().getValue() % 7 + 1;",
                "case \"Hour\" -> now.getHour();",
                "case \"Minute\" -> now.getMinute();",
                "case \"Second\" -> now.getSecond();",
                "default -> 0.0D;",
            ]);
            s.close("};");
        });
        s.blank();

        s.comment("── Ids ───────────────────────────────────────────────────");
        s.doc("Namespaces a bare path with this mod's id, the way the editor does.");
        s.braced("public static String qualify(String id)", |s| {
            s.line(format!(
                "return id.indexOf(':') >= 0 ? id : {main}.MOD_ID + \":\" + id;"
            ));
        });
        s.blank();
        s.braced("private static @Nullable Identifier parse(String id)", |s| {
            s.line("final Identifier parsed = Identifier.tryParse(qualify(id));");
            s.open("if (parsed == null) {");
            s.line(format!("{main}.LOGGER.warn(\"Stitchcraft: \\\"{{}}\\\" is not a valid id\", id);"));
            s.close("}");
            s.line("return parsed;");
        });
        s.blank();
        s.braced("public static @Nullable Block block(String id)", |s| {
            s.line("final Identifier key = parse(id);");
            s.line("return key == null ? null : BuiltInRegistries.BLOCK.getValue(key);");
        });
        s.blank();
        s.braced("public static @Nullable Item item(String id)", |s| {
            s.line("final Identifier key = parse(id);");
            s.line("return key == null ? null : BuiltInRegistries.ITEM.getValue(key);");
        });
        s.blank();
        s.braced("public static @Nullable EntityType<?> entityType(String id)", |s| {
            s.line("final Identifier key = parse(id);");
            s.line("return key == null ? null : BuiltInRegistries.ENTITY_TYPE.getValue(key);");
        });
        s.blank();

        s.comment("── Targets ───────────────────────────────────────────────");
        s.doc("Which entity a command acts on, as the canvas's dropdown named it.");
        s.braced("public enum Target", |s| {
            s.line("EVENT_PLAYER, EVENT_ENTITY, ALL_PLAYERS, NEAREST_PLAYER");
        });
        s.blank();
        s.braced("public enum Weather", |s| {
            s.line("CLEAR, RAIN, THUNDER");
        });
        s.blank();
        s.braced("public static List<ServerPlayer> players(Ctx ctx)", |s| {
            s.line("final MinecraftServer server = ctx.server;");
            s.line("return server == null ? List.of() : List.copyOf(server.getPlayerList().getPlayers());");
        });
        s.blank();
        s.doc(
            "The entities `target` names under `ctx`. An empty list is the \
             normal answer for a target the hook cannot supply, and every \
             command below is written to do nothing with one.",
        );
        s.braced("public static List<LivingEntity> resolve(Ctx ctx, Target target)", |s| {
            s.comment(
                "The type witnesses are load-bearing: `List.of(ctx.player)` is a \
                 List<ServerPlayer>, which is not a List<LivingEntity>.",
            );
            s.open("return switch (target) {");
            s.lines([
                "case EVENT_PLAYER -> ctx.player != null ? List.<LivingEntity>of(ctx.player) : List.of();",
                "case EVENT_ENTITY -> ctx.entity != null ? List.<LivingEntity>of(ctx.entity) : List.of();",
                "case ALL_PLAYERS -> List.<LivingEntity>copyOf(players(ctx));",
                "case NEAREST_PLAYER -> nearest(ctx);",
            ]);
            s.close("};");
        });
        s.blank();
        s.braced("private static List<LivingEntity> nearest(Ctx ctx)", |s| {
            s.line("final ServerPlayer player = nearestPlayer(ctx);");
            s.line("return player != null ? List.<LivingEntity>of(player) : List.of();");
        });
        s.blank();
        s.braced("private static @Nullable ServerPlayer nearestPlayer(Ctx ctx)", |s| {
            s.line("if (ctx.level == null || ctx.pos == null) return null;");
            s.line("return ctx.level.getNearestPlayer(ctx.pos.getX() + 0.5D, ctx.pos.getY() + 0.5D, ctx.pos.getZ() + 0.5D, -1.0D, false) instanceof ServerPlayer found ? found : null;");
        });
        s.blank();

        s.comment("── Commands ──────────────────────────────────────────────");
        s.braced(
            "public static void message(Ctx ctx, Target target, String text, boolean actionBar)",
            |s| {
                s.line("final Component component = Component.literal(text);");
                s.open("for (LivingEntity entity : resolve(ctx, target)) {");
                s.line("if (!(entity instanceof ServerPlayer player)) continue;");
                s.open("if (actionBar) {");
                s.line("player.displayClientMessage(component, true);");
                s.pivot("} else {");
                s.line("player.sendSystemMessage(component);");
                s.close("}");
                s.close("}");
            },
        );
        s.blank();
        s.braced("public static void broadcast(Ctx ctx, String text)", |s| {
            s.line("final Component component = Component.literal(text);");
            s.open("for (ServerPlayer player : players(ctx)) {");
            s.line("player.sendSystemMessage(component);");
            s.close("}");
        });
        s.blank();
        s.doc("Runs `command` with the server console's permissions.");
        s.braced("public static void runCommand(Ctx ctx, String command)", |s| {
            s.line("if (ctx.server == null) return;");
            s.line("ctx.server.getCommands().performPrefixedCommand(ctx.server.createCommandSourceStack(), command);");
        });
        s.blank();
        s.braced("public static void setBlock(Ctx ctx, double x, double y, double z, String id)", |s| {
            s.line("if (ctx.level == null) return;");
            s.line("final Block target = block(id);");
            s.line("if (target == null) return;");
            s.line("ctx.level.setBlockAndUpdate(pos(x, y, z), target.defaultBlockState());");
        });
        s.blank();
        s.braced("public static void breakBlock(Ctx ctx, double x, double y, double z, boolean drop)", |s| {
            s.line("if (ctx.level == null) return;");
            s.line("ctx.level.destroyBlock(pos(x, y, z), drop);");
        });
        s.blank();
        s.braced("public static void spawnEntity(Ctx ctx, String id, double x, double y, double z)", |s| {
            s.line("if (ctx.level == null) return;");
            s.line("final EntityType<?> type = entityType(id);");
            s.line("if (type == null) return;");
            s.line("final Entity spawned = type.create(ctx.level, net.minecraft.world.entity.EntitySpawnReason.COMMAND);");
            s.line("if (spawned == null) return;");
            s.line("spawned.moveTo(x, y, z, spawned.getYRot(), spawned.getXRot());");
            s.line("ctx.level.addFreshEntity(spawned);");
        });
        s.blank();
        s.braced("public static void giveItem(Ctx ctx, Target target, String id, int count)", |s| {
            s.line("final Item wanted = item(id);");
            s.line("if (wanted == null || count <= 0) return;");
            s.open("for (LivingEntity entity : resolve(ctx, target)) {");
            s.line("if (!(entity instanceof ServerPlayer player)) continue;");
            s.line("player.addItem(new ItemStack(wanted, count));");
            s.close("}");
        });
        s.blank();
        s.braced(
            "public static void playSound(Ctx ctx, String id, double x, double y, double z, float volume, float pitch)",
            |s| {
                s.line("if (ctx.level == null) return;");
                s.line("final Identifier key = parse(id);");
                s.line("if (key == null) return;");
                s.line("final Optional<Holder.Reference<SoundEvent>> sound = BuiltInRegistries.SOUND_EVENT.get(key);");
                s.line("if (sound.isEmpty()) return;");
                s.line("ctx.level.playSound(null, x, y, z, sound.get().value(), SoundSource.BLOCKS, volume, pitch);");
            },
        );
        s.blank();
        s.braced(
            "public static void spawnParticle(Ctx ctx, String id, double x, double y, double z, int count)",
            |s| {
                s.line("if (ctx.level == null || count <= 0) return;");
                s.line("final Identifier key = parse(id);");
                s.line("if (key == null) return;");
                s.comment(
                    "Only the option-less particle types can be named by id alone; \
                     anything needing extra data is not something a dropdown can \
                     describe.",
                );
                s.open("if (BuiltInRegistries.PARTICLE_TYPE.getValue(key) instanceof ParticleOptions options) {");
                s.line("ctx.level.sendParticles(options, x, y, z, count, 0.2D, 0.2D, 0.2D, 0.0D);");
                s.pivot("} else {");
                s.line(format!("{main}.LOGGER.warn(\"Stitchcraft: particle \\\"{{}}\\\" needs options and cannot be spawned by id\", id);"));
                s.close("}");
            },
        );
        s.blank();
        s.braced("public static void damage(Ctx ctx, Target target, float amount)", |s| {
            s.line("if (ctx.level == null || amount <= 0.0F) return;");
            s.open("for (LivingEntity entity : resolve(ctx, target)) {");
            s.line("entity.hurtServer(ctx.level, ctx.level.damageSources().generic(), amount);");
            s.close("}");
        });
        s.blank();
        s.braced("public static void heal(Ctx ctx, Target target, float amount)", |s| {
            s.line("if (amount <= 0.0F) return;");
            s.open("for (LivingEntity entity : resolve(ctx, target)) {");
            s.line("entity.heal(amount);");
            s.close("}");
        });
        s.blank();
        s.braced(
            "public static void addEffect(Ctx ctx, Target target, String id, int seconds, int amplifier)",
            |s| {
                s.line("final Identifier key = parse(id);");
                s.line("if (key == null) return;");
                s.line("final Optional<Holder.Reference<MobEffect>> effect = BuiltInRegistries.MOB_EFFECT.get(key);");
                s.line("if (effect.isEmpty()) return;");
                s.open("for (LivingEntity entity : resolve(ctx, target)) {");
                s.line("entity.addEffect(new MobEffectInstance(effect.get(), Math.max(1, seconds) * 20, Math.max(0, amplifier)));");
                s.close("}");
            },
        );
        s.blank();
        s.braced(
            "public static void teleport(Ctx ctx, Target target, double x, double y, double z)",
            |s| {
                s.open("for (LivingEntity entity : resolve(ctx, target)) {");
                s.line("entity.teleportTo(x, y, z);");
                s.close("}");
            },
        );
        s.blank();
        s.braced(
            "public static void push(Ctx ctx, Target target, double x, double y, double z)",
            |s| {
                s.open("for (LivingEntity entity : resolve(ctx, target)) {");
                s.line("entity.setDeltaMovement(entity.getDeltaMovement().add(new Vec3(x, y, z)));");
                s.comment("Without this the client never sees the change.");
                s.line("entity.hurtMarked = true;");
                s.close("}");
            },
        );
        s.blank();
        s.braced(
            "public static void explode(Ctx ctx, double x, double y, double z, float power, boolean fire)",
            |s| {
                s.line("if (ctx.level == null) return;");
                s.line("ctx.level.explode(null, x, y, z, power, fire, Level.ExplosionInteraction.TNT);");
            },
        );
        s.blank();
        s.braced("public static void setTimeOfDay(Ctx ctx, int time)", |s| {
            s.line("if (ctx.level == null) return;");
            s.line("ctx.level.setDayTime(time);");
        });
        s.blank();
        s.braced("public static void setWeather(Ctx ctx, Weather weather, int seconds)", |s| {
            s.line("if (ctx.level == null) return;");
            s.line("final int ticks = Math.max(1, seconds) * 20;");
            s.open("switch (weather) {");
            s.line("case CLEAR -> ctx.level.setWeatherParameters(ticks, 0, false, false);");
            s.line("case RAIN -> ctx.level.setWeatherParameters(0, ticks, true, false);");
            s.line("case THUNDER -> ctx.level.setWeatherParameters(0, ticks, true, true);");
            s.close("}");
        });
        s.blank();

        s.comment("── World reporters ───────────────────────────────────────");
        s.braced("private static BlockPos pos(double x, double y, double z)", |s| {
            s.line("return BlockPos.containing(x, y, z);");
        });
        s.blank();
        s.braced("public static String blockIdAt(Ctx ctx, double x, double y, double z)", |s| {
            s.line("if (ctx.level == null) return \"\";");
            s.line("return BuiltInRegistries.BLOCK.getKey(ctx.level.getBlockState(pos(x, y, z)).getBlock()).toString();");
        });
        s.blank();
        s.braced(
            "public static boolean isBlockAt(Ctx ctx, double x, double y, double z, String id)",
            |s| {
                s.line("return blockIdAt(ctx, x, y, z).equals(qualify(id));");
            },
        );
        s.blank();
        s.braced("public static double lightAt(Ctx ctx, double x, double y, double z)", |s| {
            s.line("if (ctx.level == null) return 0.0D;");
            s.line("return ctx.level.getMaxLocalRawBrightness(pos(x, y, z));");
        });
        s.blank();
        s.braced("public static double surfaceHeightAt(Ctx ctx, double x, double z)", |s| {
            s.line("if (ctx.level == null) return 0.0D;");
            s.line("return ctx.level.getHeight(net.minecraft.world.level.levelgen.Heightmap.Types.WORLD_SURFACE, (int) x, (int) z);");
        });
        s.blank();
        s.braced("public static boolean isDay(Ctx ctx)", |s| {
            s.line("return ctx.level != null && ctx.level.isBrightOutside();");
        });
        s.blank();
        s.braced("public static boolean isRaining(Ctx ctx)", |s| {
            s.line("return ctx.level != null && ctx.level.isRaining();");
        });
        s.blank();
        s.braced("public static double timeOfDay(Ctx ctx)", |s| {
            s.line("return ctx.level == null ? 0.0D : ctx.level.getDayTime() % 24000L;");
        });
        s.blank();
        s.braced("public static String difficulty(Ctx ctx)", |s| {
            s.line("return ctx.level == null ? \"\" : ctx.level.getDifficulty().getKey();");
        });
        s.blank();
        s.braced("public static String levelName(Ctx ctx)", |s| {
            s.line("return ctx.level == null ? \"\" : ctx.level.dimension().identifier().toString();");
        });
        s.blank();
        s.braced("public static double playerCount(Ctx ctx)", |s| {
            s.line("return players(ctx).size();");
        });
    });
    s.finish()
}

fn vars(names: &Names) -> String {
    let main = &names.main_class;
    let mut s = Source::new();
    s.line(format!("package {};", names.script_package()));
    s.blank();
    banner(
        &mut s,
        names,
        "The mod's variables, lists and dicts, and the JSON file they are saved \
         to. Everything is keyed by the name the canvas gave it, so renaming one \
         in the editor renames it here too.\n\nState is server-wide and saved \
         under the game directory rather than per world: a canvas has no notion \
         of which save it belongs to, and pretending otherwise would lose data \
         on a world switch. `Vars.load` and `Vars.save` are called from the \
         server-start and server-stop hooks.",
    );
    s.lines([
        "import com.google.gson.Gson;",
        "import com.google.gson.GsonBuilder;",
        "import com.google.gson.JsonElement;",
        "import com.google.gson.JsonObject;",
        "import com.google.gson.JsonParser;",
        "import com.google.gson.JsonPrimitive;",
        "import java.io.IOException;",
        "import java.nio.charset.StandardCharsets;",
        "import java.nio.file.Files;",
        "import java.nio.file.Path;",
        "import java.util.ArrayList;",
        "import java.util.LinkedHashMap;",
        "import java.util.List;",
        "import java.util.Map;",
        "import net.frozenblock.lib.platform.ModLoader;",
        "import org.jetbrains.annotations.Nullable;",
        format!("import {}.{main};", names.package).as_str(),
    ]);
    s.blank();
    s.braced("public final class Vars", |s| {
        s.line("private static final Gson GSON = new GsonBuilder().setPrettyPrinting().create();");
        s.blank();
        s.comment(
            "Insertion-ordered so a saved file keeps the order the canvas \
             declared things in, which makes it readable and diffable.",
        );
        s.line("private static final Map<String, Object> VARIABLES = new LinkedHashMap<>();");
        s.line("private static final Map<String, List<Object>> LISTS = new LinkedHashMap<>();");
        s.line("private static final Map<String, Map<String, Object>> DICTS = new LinkedHashMap<>();");
        s.blank();
        s.line("private Vars() {}");
        s.blank();

        s.comment("── Declarations, called once during mod init ─────────────");
        s.braced("public static void declareVariable(String name, Object initial)", |s| {
            s.line("VARIABLES.putIfAbsent(name, initial);");
        });
        s.blank();
        s.braced("public static void declareList(String name, Object... initial)", |s| {
            s.line("LISTS.computeIfAbsent(name, key -> new ArrayList<>(List.of(initial)));");
        });
        s.blank();
        s.braced("public static void declareDict(String name)", |s| {
            s.line("DICTS.computeIfAbsent(name, key -> new LinkedHashMap<>());");
        });
        s.blank();
        s.braced("public static void declareDictEntry(String name, String key, Object value)", |s| {
            s.line("declareDict(name);");
            s.line("DICTS.get(name).putIfAbsent(key, value);");
        });
        s.blank();

        s.comment("── Variables ─────────────────────────────────────────────");
        s.doc("An undeclared name reads as 0, the way it does in the editor.");
        s.braced("public static Object get(String name)", |s| {
            s.line("return VARIABLES.getOrDefault(name, Double.valueOf(0.0D));");
        });
        s.blank();
        s.braced("public static void set(String name, Object value)", |s| {
            s.line("VARIABLES.put(name, value);");
        });
        s.blank();
        s.braced("public static void change(String name, double by)", |s| {
            s.line("VARIABLES.put(name, Double.valueOf(Rt.num(get(name)) + by));");
        });
        s.blank();

        s.comment("── Lists. Indices are 1-based, as in the editor ──────────");
        s.braced("private static List<Object> list(String name)", |s| {
            s.line("return LISTS.computeIfAbsent(name, key -> new ArrayList<>());");
        });
        s.blank();
        s.doc("The 0-based position `index` names, or -1 when it is out of range.");
        s.braced("private static int at(List<Object> list, double index)", |s| {
            s.line("final int zeroBased = (int) index - 1;");
            s.line("return zeroBased >= 0 && zeroBased < list.size() ? zeroBased : -1;");
        });
        s.blank();
        s.braced("public static void listAdd(String name, Object value)", |s| {
            s.line("list(name).add(value);");
        });
        s.blank();
        s.braced("public static void listDelete(String name, double index)", |s| {
            s.line("final List<Object> items = list(name);");
            s.line("final int position = at(items, index);");
            s.line("if (position >= 0) items.remove(position);");
        });
        s.blank();
        s.braced("public static void listClear(String name)", |s| {
            s.line("list(name).clear();");
        });
        s.blank();
        s.doc("Inserting one past the end appends, which is what a drag to the bottom means.");
        s.braced("public static void listInsert(String name, double index, Object value)", |s| {
            s.line("final List<Object> items = list(name);");
            s.line("final int position = Math.max(0, Math.min(items.size(), (int) index - 1));");
            s.line("items.add(position, value);");
        });
        s.blank();
        s.braced("public static void listReplace(String name, double index, Object value)", |s| {
            s.line("final List<Object> items = list(name);");
            s.line("final int position = at(items, index);");
            s.line("if (position >= 0) items.set(position, value);");
        });
        s.blank();
        s.braced("public static Object listItem(String name, double index)", |s| {
            s.line("final List<Object> items = list(name);");
            s.line("final int position = at(items, index);");
            s.line("return position >= 0 ? items.get(position) : \"\";");
        });
        s.blank();
        s.braced("public static boolean listHas(String name, double index)", |s| {
            s.line("return at(list(name), index) >= 0;");
        });
        s.blank();
        s.braced("public static double listSize(String name)", |s| {
            s.line("return list(name).size();");
        });
        s.blank();
        s.doc("1-based position of the first loose match, or 0.");
        s.braced("public static double listIndexOf(String name, Object value)", |s| {
            s.line("final List<Object> items = list(name);");
            s.open("for (int i = 0; i < items.size(); i++) {");
            s.line("if (Rt.eq(items.get(i), value)) return i + 1;");
            s.close("}");
            s.line("return 0.0D;");
        });
        s.blank();
        s.braced("public static double listCount(String name, Object value)", |s| {
            s.line("int found = 0;");
            s.open("for (Object item : list(name)) {");
            s.line("if (Rt.eq(item, value)) found++;");
            s.close("}");
            s.line("return found;");
        });
        s.blank();
        s.braced("public static boolean listContains(String name, Object value)", |s| {
            s.line("return listIndexOf(name, value) > 0.0D;");
        });
        s.blank();
        s.braced("public static String listAsJson(String name)", |s| {
            s.line("return GSON.toJson(toJson(list(name)));");
        });
        s.blank();

        s.comment("── Dicts ─────────────────────────────────────────────────");
        s.braced("private static Map<String, Object> dict(String name)", |s| {
            s.line("return DICTS.computeIfAbsent(name, key -> new LinkedHashMap<>());");
        });
        s.blank();
        s.braced("public static void dictSet(String name, String key, Object value)", |s| {
            s.line("dict(name).put(key, value);");
        });
        s.blank();
        s.braced("public static void dictDelete(String name, String key)", |s| {
            s.line("dict(name).remove(key);");
        });
        s.blank();
        s.braced("public static void dictClear(String name)", |s| {
            s.line("dict(name).clear();");
        });
        s.blank();
        s.braced("public static Object dictGet(String name, String key)", |s| {
            s.line("return dict(name).getOrDefault(key, \"\");");
        });
        s.blank();
        s.braced("public static boolean dictHas(String name, String key)", |s| {
            s.line("return dict(name).containsKey(key);");
        });
        s.blank();
        s.braced("public static double dictSize(String name)", |s| {
            s.line("return dict(name).size();");
        });
        s.blank();
        s.doc("The keys, comma-separated, in insertion order.");
        s.braced("public static String dictKeys(String name)", |s| {
            s.line("return String.join(\",\", dict(name).keySet());");
        });
        s.blank();
        s.braced("public static String dictAsJson(String name)", |s| {
            s.line("final JsonObject out = new JsonObject();");
            s.open("for (Map.Entry<String, Object> entry : dict(name).entrySet()) {");
            s.line("out.add(entry.getKey(), toJson(entry.getValue()));");
            s.close("}");
            s.line("return GSON.toJson(out);");
        });
        s.blank();

        s.comment("── Saving ────────────────────────────────────────────────");
        s.braced("private static Path file()", |s| {
            s.line(format!(
                "return ModLoader.getGameDir().resolve(\"stitchcraft\").resolve({main}.MOD_ID + \".json\");"
            ));
        });
        s.blank();
        s.braced("private static JsonElement toJson(@Nullable Object value)", |s| {
            s.line("if (value instanceof Number n) return new JsonPrimitive(n);");
            s.line("if (value instanceof Boolean b) return new JsonPrimitive(b);");
            s.line("return new JsonPrimitive(Rt.str(value));");
        });
        s.blank();
        s.braced("private static JsonElement toJson(List<Object> items)", |s| {
            s.line("final com.google.gson.JsonArray out = new com.google.gson.JsonArray();");
            s.line("for (Object item : items) out.add(toJson(item));");
            s.line("return out;");
        });
        s.blank();
        s.doc(
            "Reads a saved primitive back into the three types a canvas value \
             can hold. Anything else in a hand-edited file becomes its text.",
        );
        s.braced("private static Object fromJson(JsonElement element)", |s| {
            s.line("if (!(element instanceof JsonPrimitive primitive)) return element.toString();");
            s.line("if (primitive.isBoolean()) return primitive.getAsBoolean();");
            s.line("if (primitive.isNumber()) return Double.valueOf(primitive.getAsDouble());");
            s.line("return primitive.getAsString();");
        });
        s.blank();
        s.braced("public static void save()", |s| {
            s.open("try {");
            s.line("final JsonObject root = new JsonObject();");
            s.line("final JsonObject variables = new JsonObject();");
            s.open("for (Map.Entry<String, Object> entry : VARIABLES.entrySet()) {");
            s.line("variables.add(entry.getKey(), toJson(entry.getValue()));");
            s.close("}");
            s.line("root.add(\"variables\", variables);");
            s.line("final JsonObject lists = new JsonObject();");
            s.open("for (Map.Entry<String, List<Object>> entry : LISTS.entrySet()) {");
            s.line("lists.add(entry.getKey(), toJson(entry.getValue()));");
            s.close("}");
            s.line("root.add(\"lists\", lists);");
            s.line("final JsonObject dicts = new JsonObject();");
            s.open("for (Map.Entry<String, Map<String, Object>> entry : DICTS.entrySet()) {");
            s.line("final JsonObject one = new JsonObject();");
            s.open("for (Map.Entry<String, Object> pair : entry.getValue().entrySet()) {");
            s.line("one.add(pair.getKey(), toJson(pair.getValue()));");
            s.close("}");
            s.line("dicts.add(entry.getKey(), one);");
            s.close("}");
            s.line("root.add(\"dicts\", dicts);");
            s.line("final Path path = file();");
            s.line("Files.createDirectories(path.getParent());");
            s.line("Files.writeString(path, GSON.toJson(root), StandardCharsets.UTF_8);");
            s.pivot("} catch (IOException e) {");
            s.line(format!("{main}.LOGGER.error(\"Stitchcraft: could not save mod state\", e);"));
            s.close("}");
        });
        s.blank();
        s.doc(
            "Loads what was saved over the declared defaults. A name that is no \
             longer declared is dropped, so deleting a variable in the editor \
             does not leave it behind in the save file.",
        );
        s.braced("public static void load()", |s| {
            s.line("final Path path = file();");
            s.line("if (!Files.exists(path)) return;");
            s.open("try {");
            s.line("final JsonObject root = JsonParser.parseString(Files.readString(path, StandardCharsets.UTF_8)).getAsJsonObject();");
            s.open("if (root.has(\"variables\")) {");
            s.open("for (Map.Entry<String, JsonElement> entry : root.getAsJsonObject(\"variables\").entrySet()) {");
            s.line("if (VARIABLES.containsKey(entry.getKey())) VARIABLES.put(entry.getKey(), fromJson(entry.getValue()));");
            s.close("}");
            s.close("}");
            s.open("if (root.has(\"lists\")) {");
            s.open("for (Map.Entry<String, JsonElement> entry : root.getAsJsonObject(\"lists\").entrySet()) {");
            s.line("if (!LISTS.containsKey(entry.getKey())) continue;");
            s.line("final List<Object> items = new ArrayList<>();");
            s.line("for (JsonElement item : entry.getValue().getAsJsonArray()) items.add(fromJson(item));");
            s.line("LISTS.put(entry.getKey(), items);");
            s.close("}");
            s.close("}");
            s.open("if (root.has(\"dicts\")) {");
            s.open("for (Map.Entry<String, JsonElement> entry : root.getAsJsonObject(\"dicts\").entrySet()) {");
            s.line("if (!DICTS.containsKey(entry.getKey())) continue;");
            s.line("final Map<String, Object> one = new LinkedHashMap<>();");
            s.open("for (Map.Entry<String, JsonElement> pair : entry.getValue().getAsJsonObject().entrySet()) {");
            s.line("one.put(pair.getKey(), fromJson(pair.getValue()));");
            s.close("}");
            s.line("DICTS.put(entry.getKey(), one);");
            s.close("}");
            s.close("}");
            s.pivot("} catch (Exception e) {");
            s.line(format!("{main}.LOGGER.error(\"Stitchcraft: could not read saved mod state\", e);"));
            s.close("}");
        });
    });
    s.finish()
}

fn scheduler(names: &Names) -> String {
    let main = &names.main_class;
    let mut s = Source::new();
    s.line(format!("package {};", names.script_package()));
    s.blank();
    banner(
        &mut s,
        names,
        "What makes `after N ticks` work: a queue drained on the server tick, \
         plus the tick counter `ticks since start` reads.\n\nA delayed body \
         keeps the context it was scheduled with, so `the event player` still \
         means the player the event was about - even though that event is long \
         over by the time it runs.",
    );
    s.lines([
        "import java.util.ArrayList;",
        "import java.util.List;",
        "import net.minecraft.server.MinecraftServer;",
        format!("import {}.{main};", names.package).as_str(),
    ]);
    s.blank();
    s.braced("public final class Scheduler", |s| {
        s.doc("What a delayed body compiles to.");
        s.braced("public interface Delayed", |s| {
            s.line("void run(Ctx ctx, Object[] args);");
        });
        s.blank();
        s.line("private record Entry(long dueAt, Ctx ctx, Object[] args, Delayed body) {}");
        s.blank();
        s.line("private static final List<Entry> PENDING = new ArrayList<>();");
        s.line("private static long ticks;");
        s.blank();
        s.line("private Scheduler() {}");
        s.blank();
        s.braced("public static double tickCount()", |s| {
            s.line("return ticks;");
        });
        s.blank();
        s.doc("Queues `body` to run `delay` ticks from now. A delay of 0 or less runs next tick.");
        s.braced("public static void after(int delay, Ctx ctx, Object[] args, Delayed body)", |s| {
            s.line("PENDING.add(new Entry(ticks + Math.max(1, delay), ctx, args, body));");
        });
        s.blank();
        s.doc(
            "Called from the server tick hook. Bodies due this tick are taken \
             out of the queue before any of them runs, so one that schedules \
             another does not spin.",
        );
        s.braced("public static void tick(MinecraftServer server)", |s| {
            s.line("ticks++;");
            s.line("if (PENDING.isEmpty()) return;");
            s.line("final List<Entry> due = new ArrayList<>();");
            s.open("for (int i = PENDING.size() - 1; i >= 0; i--) {");
            s.open("if (PENDING.get(i).dueAt() <= ticks) {");
            s.line("due.add(PENDING.remove(i));");
            s.close("}");
            s.close("}");
            s.open("for (Entry entry : due) {");
            s.open("try {");
            s.line("entry.body().run(entry.ctx(), entry.args());");
            s.pivot("} catch (Exception e) {");
            s.line(format!(
                "{main}.LOGGER.error(\"Stitchcraft: a delayed block failed\", e);"
            ));
            s.close("}");
            s.close("}");
        });
        s.blank();
        s.doc("Drops everything queued, so a restart does not replay the last session.");
        s.braced("public static void clear()", |s| {
            s.line("PENDING.clear();");
            s.line("ticks = 0L;");
        });
    });
    s.finish()
}
